# Generated by Django 3.2.18 on 2023-08-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
